// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: cbt_bot_llm_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CBTBotService_Chat_FullMethodName = "/cbt_bot.CBTBotService/Chat"
)

// CBTBotServiceClient is the client API for CBTBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CBTBotServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
}

type cBTBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCBTBotServiceClient(cc grpc.ClientConnInterface) CBTBotServiceClient {
	return &cBTBotServiceClient{cc}
}

func (c *cBTBotServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CBTBotService_ServiceDesc.Streams[0], CBTBotService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CBTBotService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

// CBTBotServiceServer is the server API for CBTBotService service.
// All implementations must embed UnimplementedCBTBotServiceServer
// for forward compatibility.
type CBTBotServiceServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	mustEmbedUnimplementedCBTBotServiceServer()
}

// UnimplementedCBTBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCBTBotServiceServer struct{}

func (UnimplementedCBTBotServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedCBTBotServiceServer) mustEmbedUnimplementedCBTBotServiceServer() {}
func (UnimplementedCBTBotServiceServer) testEmbeddedByValue()                       {}

// UnsafeCBTBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CBTBotServiceServer will
// result in compilation errors.
type UnsafeCBTBotServiceServer interface {
	mustEmbedUnimplementedCBTBotServiceServer()
}

func RegisterCBTBotServiceServer(s grpc.ServiceRegistrar, srv CBTBotServiceServer) {
	// If the following call pancis, it indicates UnimplementedCBTBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CBTBotService_ServiceDesc, srv)
}

func _CBTBotService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CBTBotServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CBTBotService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

// CBTBotService_ServiceDesc is the grpc.ServiceDesc for CBTBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CBTBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cbt_bot.CBTBotService",
	HandlerType: (*CBTBotServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _CBTBotService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cbt_bot_llm_stream.proto",
}
