# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbt_bot_llm_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cbt_bot_llm_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63\x62t_bot_llm_stream.proto\x12\x07\x63\x62t_bot\"/\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x96\x01\n\x0c\x43hatResponse\x12\x1c\n\x14\x63onsultationResponse\x18\x01 \x01(\t\x12)\n\x0b\x63\x62tResponse\x18\x02 \x01(\x0b\x32\x14.cbt_bot.CBTQuestion\x12=\n\x10\x61nalysisResponse\x18\x03 \x01(\x0b\x32#.cbt_bot.ConsultationAnalysisReport\"\xf3\x02\n\x1a\x43onsultationAnalysisReport\x12\x13\n\x0b\x63\x62tCategory\x18\x01 \x01(\t\x12\x19\n\x11\x63onsultationStage\x18\x02 \x01(\t\x12\x1b\n\x13triggeringSituation\x18\x03 \x01(\t\x12\x19\n\x11\x61utomaticThoughts\x18\x04 \x01(\t\x12\x10\n\x08\x65motions\x18\x05 \x03(\t\x12W\n\x12intensityOfEmotion\x18\x06 \x03(\x0b\x32;.cbt_bot.ConsultationAnalysisReport.IntensityOfEmotionEntry\x12\x19\n\x11underlyingBeliefs\x18\x07 \x01(\t\x12\x14\n\x0cuserResponse\x18\x08 \x01(\t\x12\x16\n\x0etherapistNotes\x18\t \x01(\t\x1a\x39\n\x17IntensityOfEmotionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\">\n\x0b\x43\x42TQuestion\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x0f\n\x07\x63hoices\x18\x03 \x03(\t\"9\n\x0c\x43\x42TQuestions\x12)\n\x0b\x63\x62tQuestion\x18\x01 \x03(\x0b\x32\x14.cbt_bot.CBTQuestion2F\n\rCBTBotService\x12\x35\n\x04\x43hat\x12\x14.cbt_bot.ChatRequest\x1a\x15.cbt_bot.ChatResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cbt_bot_llm_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTATIONANALYSISREPORT_INTENSITYOFEMOTIONENTRY']._loaded_options = None
  _globals['_CONSULTATIONANALYSISREPORT_INTENSITYOFEMOTIONENTRY']._serialized_options = b'8\001'
  _globals['_CHATREQUEST']._serialized_start=37
  _globals['_CHATREQUEST']._serialized_end=84
  _globals['_CHATRESPONSE']._serialized_start=87
  _globals['_CHATRESPONSE']._serialized_end=237
  _globals['_CONSULTATIONANALYSISREPORT']._serialized_start=240
  _globals['_CONSULTATIONANALYSISREPORT']._serialized_end=611
  _globals['_CONSULTATIONANALYSISREPORT_INTENSITYOFEMOTIONENTRY']._serialized_start=554
  _globals['_CONSULTATIONANALYSISREPORT_INTENSITYOFEMOTIONENTRY']._serialized_end=611
  _globals['_CBTQUESTION']._serialized_start=613
  _globals['_CBTQUESTION']._serialized_end=675
  _globals['_CBTQUESTIONS']._serialized_start=677
  _globals['_CBTQUESTIONS']._serialized_end=734
  _globals['_CBTBOTSERVICE']._serialized_start=736
  _globals['_CBTBOTSERVICE']._serialized_end=806
# @@protoc_insertion_point(module_scope)
